'use strict';

module.exports = {
    rules: {
        'align': [true, 'parameters', 'statements'],
        'array-type': [true, 'array-simple'],
        'arrow-parens': true,
        'arrow-return-shorthand': true,
        'binary-expression-operand-order': true,
        'callable-types': true,
        'class-name': true,
        'comment-format': [true, 'check-space'],
        'completed-docs': false,
        'encoding': true,
        'file-header': false,
        'import-spacing': true,
        'interface-name': [true, 'always-prefix'],
        'interface-over-type-literal': true,
        'jsdoc-format': true,
        'match-default-export-name': false,
        'newline-before-return': true,
        'newline-per-chained-call': false,
        'new-parens': true,
        'no-angle-bracket-type-assertion': true,
        'no-boolean-literal-compare': false,
        'no-consecutive-blank-lines': [true, 2],
        'no-irregular-whitespace': true,
        'no-parameter-properties': false,
        'no-redundant-jsdoc': false,
        'no-reference-import': true,
        'no-trailing-whitespace': true,
        'no-unnecessary-callback-wrapper': true,
        'no-unnecessary-initializer': true,
        'no-unnecessary-qualifier': false,
        'number-literal-format': true,
        'object-literal-key-quotes': [true, 'consistent-as-needed'],
        'object-literal-shorthand': true,
        'one-line': [true,
            'check-catch',
            'check-finally',
            'check-else',
            'check-open-brace',
            'check-whitespace',
        ],
        'one-variable-per-declaration': true,
        'ordered-imports': [true, {
            'import-sources-order': 'lowercase-last',
            'grouped-imports': true,
            'module-source-path': 'full',
            'named-imports-order': 'lowercase-last',
        }],
        'prefer-function-over-method': true,
        'prefer-method-signature': true,
        'prefer-switch': false,
        'prefer-template': [true, 'allow-single-concat'],
        'quotemark': [true, 'single', 'jsx-double', 'avoid-template', 'avoid-escape'],
        'return-undefined': true,
        'semicolon': [true, 'always'],
        'space-before-function-paren': [true, {
            anonymous: 'always',
            named: 'never',
            asyncArrow: 'always',
            constructor: 'never',
            method: 'never',
        }],
        'space-within-parens': [true, 0],
        'switch-final-break': [true, 'always'],
        'type-literal-delimiter': true,
        'variable-name': [true,
            'check-format',
            'allow-pascal-case',
            'ban-keywords',
        ],
        'whitespace': [
            'check-branch',
            'check-decl',
            'check-operator',
            'check-module',
            'check-separator',
            'check-rest-spread',
            'check-type',
            'check-typecast',
            'check-type-operator',
            'check-preblock',
        ],
    },
};
