'use strict';

module.exports = {
    rules: {
        'adjacent-overload-signatures': true,
        'ban-types': [true,
            ['Object', 'Avoid using the `Object` type. Did you mean `object`?'],
            ['Function', 'Avoid using the `Function` type. Prefer a specific function type, like `() => void`.'],
            ['Boolean', 'Avoid using the `Boolean` type. Did you mean `boolean`?'],
            ['Number', 'Avoid using the `Number` type. Did you mean `number`?'],
            ['String', 'Avoid using the `String` type. Did you mean `string`?'],
            ['Symbol', 'Avoid using the `Symbol` type. Did you mean `symbol`?'],
        ],
        'member-access': true,
        'member-ordering': [true, {
            order: 'statics-first',
        }],
        'no-any': true,
        'no-empty-interface': true,
        'no-import-side-effect': false,
        'no-inferrable-types': false,
        'no-internal-module': true,
        'no-magic-numbers': false,
        'no-namespace': true,
        'no-non-null-assertion': false,
        'no-parameter-reassignment': false,
        'no-reference': true,
        'no-unnecessary-type-assertion': false,
        'no-var-requires': true,
        'only-arrow-functions': [true,
            'allow-declarations',
            'allow-named-functions',
        ],
        'prefer-for-of': true,
        'promise-function-async': false,
        'typedef': false,
        'typedef-whitespace': [true, {
            'call-signature': 'nospace',
            'index-signature': 'nospace',
            'parameter': 'nospace',
            'property-declaration': 'nospace',
            'variable-declaration': 'nospace',
        }, {
            'call-signature': 'onespace',
            'index-signature': 'onespace',
            'parameter': 'onespace',
            'property-declaration': 'onespace',
            'variable-declaration': 'onespace',
        }],
        'unified-signatures': true,
    },
};
